//THIS FILE IS AUTOMATICALLY GENERATED BY BYONDAPI_TEST, PLEASE DO NOT TOUCH IT
//PROC DEFINITIONS MAY MOVE AROUND, THIS IS NORMAL

/* This comment bypasses grep checks */ /var/__byondapi_test

/proc/__detect_byondapi_test()
	if (world.system_type == UNIX)
		return __byondapi_test = "libbyondapi_test"
	else
		return __byondapi_test = "byondapi_test"

#define BYONDAPI_TEST (__byondapi_test || __detect_byondapi_test())

///Tests macro style binds
var/static/loaded_byondapi_test_test_new_obj_macro_ffi = load_ext(BYONDAPI_TEST, "byond:test_new_obj_macro_ffi")
#define test_new_obj_macro_ffi(_object, _number, _thing) call_ext(loaded_byondapi_test_test_new_obj_macro_ffi)(_object, _number, _thing)

///Tests new
/proc/test_new_obj()
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_new_obj_ffi")
	return call_ext(loaded)()

///Tests lists read
/proc/test_list_read(list)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_list_read_ffi")
	return call_ext(loaded)(list)

///Tests non-assoc lists
/proc/test_non_assoc_list(list)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_non_assoc_list_ffi")
	return call_ext(loaded)(list)

///Tests ref
/proc/test_ref(turf)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_ref_ffi")
	return call_ext(loaded)(turf)

///Tests lists lookup
/proc/test_list_key_lookup(list)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_list_key_lookup_ffi")
	return call_ext(loaded)(list)

///Tests length with strings
/proc/test_length_with_str(object)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_length_with_str_ffi")
	return call_ext(loaded)(object)

///Tests block
/proc/test_block()
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_block_ffi")
	return call_ext(loaded)()

///Tests lists length
/proc/test_length_with_list(list)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_length_with_list_ffi")
	return call_ext(loaded)(list)

///Tests lists popping
/proc/test_list_pop(list)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_list_pop_ffi")
	return call_ext(loaded)(list)

///Tests lists indexing
/proc/test_list_index(list)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_list_index_ffi")
	return call_ext(loaded)(list)

///Tests lists
/proc/test_list_double(list)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_list_double_ffi")
	return call_ext(loaded)(list)

///Tests list pushes
/proc/test_list_push(list)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_list_push_ffi")
	return call_ext(loaded)(list)

///Tests readwrite vars
/proc/test_readwrite_var(object)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_readwrite_var_ffi")
	return call_ext(loaded)(object)

///Tests proccalls
/proc/test_proc_call(object)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_proc_call_ffi")
	return call_ext(loaded)(object)

///Tests pointers
/proc/test_ptr(ptr)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_ptr_ffi")
	return call_ext(loaded)(ptr)

///Tests raw args binds
/proc/test_args(...)
	var/list/args_copy = args.Copy()
	args_copy.Insert(1, src)
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_args_ffi")
	return call_ext(loaded)(arglist(args_copy))

///Tests main lib connection
/proc/test_connection()
	var/static/loaded = load_ext(BYONDAPI_TEST, "byond:test_connection_ffi")
	return call_ext(loaded)()

