//THIS FILE IS AUTOMATICALLY GENERATED BY BYONDAPI_TEST, PLEASE DO NOT TOUCH IT
//PROC DEFINITIONS MAY MOVE AROUND, THIS IS NORMAL

/* This comment bypasses grep checks */ /var/__byondapi_test

/proc/__detect_byondapi_test()
	if (world.system_type == UNIX)
		return __byondapi_test = "libbyondapi_test"
	else
		return __byondapi_test = "byondapi_test"

#define BYONDAPI_TEST (__byondapi_test || __detect_byondapi_test())
    
/proc/test_new_obj()
	return call_ext(BYONDAPI_TEST, "byond:test_new_obj_ffi")()

/proc/test_list_read(list)
	return call_ext(BYONDAPI_TEST, "byond:test_list_read_ffi")(list)

/proc/test_non_assoc_list(list)
	return call_ext(BYONDAPI_TEST, "byond:test_non_assoc_list_ffi")(list)

/proc/test_ref(turf)
	return call_ext(BYONDAPI_TEST, "byond:test_ref_ffi")(turf)

/proc/test_list_key_lookup(list)
	return call_ext(BYONDAPI_TEST, "byond:test_list_key_lookup_ffi")(list)

/proc/test_length_with_str(object)
	return call_ext(BYONDAPI_TEST, "byond:test_length_with_str_ffi")(object)

/proc/test_block()
	return call_ext(BYONDAPI_TEST, "byond:test_block_ffi")()

/proc/test_length_with_list(list)
	return call_ext(BYONDAPI_TEST, "byond:test_length_with_list_ffi")(list)

/proc/test_list_pop(list)
	return call_ext(BYONDAPI_TEST, "byond:test_list_pop_ffi")(list)

/proc/test_list_index(list)
	return call_ext(BYONDAPI_TEST, "byond:test_list_index_ffi")(list)

/proc/test_list_double(list)
	return call_ext(BYONDAPI_TEST, "byond:test_list_double_ffi")(list)

/proc/test_list_push(list)
	return call_ext(BYONDAPI_TEST, "byond:test_list_push_ffi")(list)

/proc/test_readwrite_var(object)
	return call_ext(BYONDAPI_TEST, "byond:test_readwrite_var_ffi")(object)

/proc/test_proc_call(object)
	return call_ext(BYONDAPI_TEST, "byond:test_proc_call_ffi")(object)

/proc/test_ptr(ptr)
	return call_ext(BYONDAPI_TEST, "byond:test_ptr_ffi")(ptr)

/proc/test_args(...)
	var/list/args_copy = args.Copy()
	args_copy.Insert(1, src)
	return call_ext(BYONDAPI_TEST, "byond:test_args_ffi")(arglist(args_copy))

/proc/test_connection()
	return call_ext(BYONDAPI_TEST, "byond:test_connection_ffi")()

