// Ignore style warnings for for byondapi-c bindings
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::missing_safety_doc)]

// Include byondapi-c bindings (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
